import type { CombinedResume } from "@/lib/types";

export const resume: CombinedResume = {
  name: "Mohit Kumar",
  roleTitle: "Full Stack Software Engineer",
  tagline: ".NET · React · Next.js · Python/FastAPI · AI",
  contact: [
    "mohitkumarjokae@gmail.com",
    "+91 7015325817",
    "Shahbad, Kurukshetra, India",
    "linkedin.com/in/mohitkumarkojae",
    "mohitjokae.vercel.app",
  ],
  summary:
    "Full Stack Software Engineer with 5+ years of experience designing, developing and supporting enterprise-scale applications for Government of Punjab NIC projects. Strong hands-on expertise in C#, .NET, ASP.NET Core, Minimal APIs, Clean/N-Layer Architecture, PostgreSQL, React, Next.js, TypeScript, Docker and Kubernetes. Currently serving as Lead Developer and Technical Reviewer across multiple enterprise projects, including the BBMB 13-module platform. Experienced in reusable .NET frameworks, authentication/SSO integration, microservices, production troubleshooting, API integration and end-to-end feature ownership. Also have ~1 year of hands-on Python/FastAPI and AI application development.",
  focus: [
    {
      key: "dotnet",
      title: ".NET",
      badge: ".NET",
      summary: [
        "Enterprise backend specialist with 5+ years shipping government-grade applications on C# and .NET 7/8/9/10. I architect Clean, N-Layer and Vertical Slice solutions, build Minimal/Web APIs with Entity Framework & LINQ on PostgreSQL, and deploy them on Docker, Kubernetes, IIS and Linux.",
        "Beyond backend, I deliver complete full-stack products — React.js, Next.js and Tailwind frontends with Blazor where it fits. I also design reusable .NET libraries (FlowCore) consumed via NuGet to standardize capabilities across projects.",
      ],
      highlights: [
        "SPORTS, LBPAMS, PAMS election platform, Guest House & BBMB 13-module enterprise platform",
        "Reusable FlowCore .NET framework distributed via NuGet",
        "SMS gateway management with .NET 9 Minimal APIs + Server-Sent Events",
      ],
    },
    {
      key: "python",
      title: "Python & AI",
      badge: "Python",
      summary: [
        "Hands-on Python experience of approximately 1 year building fast, modern APIs with FastAPI and integrating AI workflows into real products.",
        "Built a face-recognition authentication & attendance platform wired to government face-recognition APIs and .NET SSO, plus a reusable AI chatbot package that scans PDFs/document content with Tesseract OCR and answers questions via the Groq SDK — both with React + Next.js frontends.",
      ],
      highlights: [
        "Face-recognition authentication & attendance platform (FastAPI + .NET SSO)",
        "Reusable AI chatbot package with Tesseract OCR + Groq SDK",
        "FastAPI API orchestration for AI and document-intelligence workflows",
      ],
    },
  ],
  skills: [
    { label: "Languages", value: "C#, Python, TypeScript, JavaScript, SQL" },
    { label: "Backend", value: ".NET 7/8/9/10, ASP.NET Core, Minimal APIs, Web API, MVC, FastAPI, Entity Framework, LINQ, Node.js" },
    { label: "Frontend", value: "React.js, Next.js, TypeScript, Tailwind CSS, Bootstrap, HTML5, CSS3, jQuery, Blazor" },
    { label: "Databases", value: "PostgreSQL, SQL Server, Redis" },
    { label: "Architecture", value: "Clean Architecture, N-Layer Architecture, Vertical Slice Architecture, Microservices, REST APIs, reusable packages/libraries, SSO" },
    { label: "DevOps / Cloud", value: "Docker, Kubernetes, IIS, Linux/Windows deployments, Jenkins, Git, Azure DevOps, Azure, AWS" },
    { label: "AI / Integration", value: "Face Recognition APIs, Tesseract OCR, Groq SDK, document text extraction, chatbot/QA workflows, API/tool integration" },
    { label: "AI Engineering", value: "AI coding agents, agent-assisted development, API/tool integration, security-aware code review" },
  ],
  jobs: [
    {
      title: "Senior .NET Developer (Full Stack & Lead)",
      company: "Akiko Sherman Infotech Pvt. Ltd. (Vendor to NIC Punjab)",
      location: "Punjab NIC, Mini Secretariat",
      start: "2024-06",
      points: [
        "Lead development, technical review and ongoing enhancements across multiple NIC Punjab enterprise applications, with responsibility for architecture, implementation quality and production support.",
        "Lead development and enhancements of SPORTS, a state-level platform for player registrations, tournament participation, certificates, awards and government scrutiny workflows.",
        "Manage LBPAMS (Local Bodies Poll Monitoring System) for Nagar Panchayat, Zila Parishad and Municipal elections.",
        "Serve as Lead Developer and Technical Reviewer for the BBMB enterprise platform, a planned 3-year program covering 13 interconnected modules and services.",
        "BBMB currently starts with the Budget module as a core source, with Payroll and Finance as interconnected modules; shared FlowCore workflow/file-processing capabilities and centralized authentication/SSO are being designed for reuse across these projects.",
        "Design and implement full-stack solutions using C#, .NET, Minimal APIs, React, Next.js, TypeScript, Tailwind, PostgreSQL, Entity Framework, Docker and Kubernetes.",
        "Develop and review enterprise services using Vertical Slice Architecture, reusable .NET libraries; deploy and troubleshoot applications on Linux, Docker and Kubernetes.",
        "Develop FlowCore, a reusable .NET package/framework for standardized file movement and workflow processing, intended for adoption across multiple enterprise projects through NuGet.",
        "Contribute to the Guest House project built with the MERN stack; primarily responsible for TypeScript, React and Next.js development, with limited backend involvement, while also performing technical review and lead-development responsibilities.",
      ],
      stack: "C#, .NET 8/9/10, Minimal APIs, MVC, React.js, Next.js, TypeScript, Tailwind, PostgreSQL, Entity Framework, Docker, Kubernetes, IIS, Clean Architecture, Microservices, SSO, reusable .NET libraries",
    },
    {
      title: ".NET Backend Lead Developer",
      company: "Velocis Systems Pvt. Ltd. (Vendor to NIC Punjab)",
      location: "Punjab NIC, Mini Secretariat",
      start: "2022-07",
      end: "2024-05",
      points: [
        "Architected and developed PAMS, an election monitoring platform for Vidhan Sabha and Lok Sabha elections.",
        "Designed N-Layer architecture and database schemas; built APIs using C#, .NET 8, Entity Framework and LINQ with PostgreSQL, Redis and SignalR.",
        "Handled IIS deployments, production rollouts, troubleshooting and application support.",
        "Received Appreciation from CEO Punjab for successful PAMS implementation.",
      ],
      stack: ".NET 8, MVC, N-Layer, PostgreSQL, Redis, SignalR, Entity Framework, IIS, LINQ",
    },
    {
      title: "Web Designer / Junior Developer",
      company: "Triitans Solitaire Pvt. Ltd.",
      location: "On-site",
      start: "2021-07",
      end: "2022-06",
      points: [
        "Designed and developed 5–6 responsive websites using HTML, CSS, Bootstrap, jQuery and JavaScript.",
        "Collaborated with the design team on UI/UX improvements and cross-browser compatibility.",
      ],
      stack: "HTML, CSS, Bootstrap, jQuery, JavaScript",
    },
  ],
  projects: [
    { name: "BBMB Enterprise Platform", period: "2025 – Present", org: "NIC Punjab", summary: "13-module enterprise platform delivered as a planned 3-year program. The Budget module is a core source, with Payroll and Finance as interconnected modules. Serving as Lead Developer and Technical Reviewer, with shared FlowCore workflow/file processing and centralized Auth/SSO designed for reuse across the enterprise modules.", tags: [".NET", "Microservices", "Vertical Slice Architecture", "PostgreSQL", "React", "Next.js", "TypeScript", "FlowCore", "Auth/SSO"], track: "dotnet" },
    { name: "Guest House Management Project", period: "Current", org: "NIC Punjab", summary: "MERN-based enterprise application. Primary responsibility is TypeScript, React and Next.js development, with limited backend involvement. Also contributing as Lead Developer and Technical Reviewer for implementation quality and technical decisions.", tags: ["MongoDB", "Express", "React", "Node.js", "TypeScript", "Next.js"], track: "dotnet" },
    { name: "SPORTS Management System", period: "2025 – 2026", org: "NIC Punjab", summary: "State-level platform for player registration, tournament participation, certificates, awards and government scrutiny workflows.", tags: [".NET", "React", "Next.js", "PostgreSQL"], track: "dotnet" },
    { name: "LBPAMS", period: "2024 – Present", org: "NIC Punjab", summary: "Local Bodies Poll Monitoring System for Nagar Panchayat, Zila Parishad and Municipal elections.", tags: [".NET", "Elections", "Monitoring"], track: "dotnet" },
    { name: "PAMS", period: "2023 – 2024", org: "NIC Punjab", summary: "Election monitoring system for Vidhan Sabha and Lok Sabha elections with real-time data using SignalR and Redis.", tags: [".NET 8", "PostgreSQL", "SignalR", "Redis"], track: "dotnet" },
    { name: "SMS Management System", period: "Jul – Aug 2025", org: "NIC Punjab", summary: "Centralized SMS gateway management system using .NET 9 Minimal APIs, Server-Sent Events and React + Next.js.", tags: [".NET 9 Minimal APIs", "SSE", "React", "Next.js"], track: "dotnet" },
    { name: "FlowCore", period: "Current", org: "NIC Punjab", summary: "Reusable .NET framework/package for standardized file movement and workflow processing, integrated by consumer applications through NuGet and intended for reuse across enterprise projects.", tags: [".NET Library", "NuGet", "Workflow", "File Processing"], track: "dotnet" },
    { name: "Face Recognition Authentication & Attendance Platform", period: "Hands-on", org: "NIC Punjab", summary: "Built a face-recognition platform using Python and FastAPI for authentication and attendance, integrated with government verification APIs and .NET authentication/SSO, with a React + Next.js frontend.", tags: ["Python", "FastAPI", "Face Recognition", "React", "Next.js", ".NET SSO"], track: "python" },
    { name: "Reusable AI Chatbot Package", period: "Hands-on", org: "NIC Punjab", summary: "Developed a reusable chatbot package using Python/FastAPI, Tesseract OCR and Groq SDK to process project data, PDFs/documents and web content, with React + Next.js integration.", tags: ["Python", "FastAPI", "Tesseract OCR", "Groq SDK", "React", "Next.js"], track: "python" },
    { name: "OmMedia Solution", period: "Jun – Jul 2024", org: "Personal Project", summary: "Family business management system for a printing company using .NET 8 Web API, PostgreSQL and Blazor WebAssembly with automated invoicing.", tags: [".NET 8", "Blazor", "PostgreSQL"], track: "dotnet" },
    { name: "OmMedia Mobile App", period: "Jun – Jul 2024", org: "Personal Project", summary: "Blazor Hybrid MAUI companion app for in-field photo capture of client requirements, synchronized in real time with the backend operator panel.", tags: ["Blazor Hybrid MAUI", "Mobile", "Real-time"], track: "dotnet" },
  ],
  aiProjects: [
    {
      name: "Face Recognition Authentication & Attendance Platform",
      period: "Hands-on",
      timeline: "Python / FastAPI / React / Next.js / .NET Integration",
      org: "NIC Punjab",
      summary: "Built a face-recognition platform using Python and FastAPI for authentication and attendance, integrated with government verification APIs and .NET authentication/SSO, with a React + Next.js frontend.",
      tags: ["Python", "FastAPI", "Face Recognition", "React"],
      track: "python",
      details: [
        "Integrated APIs provided by a government system for face-recognition/verification workflows.",
        "Integrated .NET authentication and SSO APIs with the Python services to connect the recognition workflow with the existing identity layer.",
        "Developed the frontend using React + Next.js and connected it to the FastAPI and .NET APIs.",
        "Implemented an end-to-end flow covering user authentication, face verification, successful identification and attendance capture.",
      ],
    },
    {
      name: "Reusable AI Chatbot Package",
      period: "Hands-on",
      timeline: "Python / FastAPI / React / Next.js / Tesseract / Groq SDK",
      org: "NIC Punjab",
      summary: "Developed a reusable chatbot package that integrates into other applications to answer questions using project data, PDFs/documents and web content.",
      tags: ["Python", "FastAPI", "OCR", "Groq"],
      track: "python",
      details: [
        "Built Python/FastAPI APIs for chatbot orchestration and application integration.",
        "Used Tesseract OCR to scan documents and extract text for downstream question answering.",
        "Integrated the Groq SDK to process and search extracted PDF/document content and web content for relevant answers.",
        "Designed the package for installation/integration into existing projects rather than as a standalone chatbot only.",
        "Built the frontend experience using React + Next.js and integrated it with the backend APIs.",
      ],
    },
  ],
  personalProjects: [],
  education: ["B.Tech – Computer Science & Engineering | Kurukshetra University | 2017 – 2021 | 72%"],
  achievements: [
    "Appreciation from CEO Punjab for successful implementation of the PAMS Project.",
    "Led full-stack and backend teams for NIC Punjab projects with 100% on-time delivery.",
  ],
  languages: "English: Professional Working Proficiency  |  Hindi: Full Professional Proficiency  |  Punjabi: Professional Working Proficiency",
  downloads: [
    { label: "PDF", href: "api/download?format=pdf", kind: "pdf" },
    { label: "Word", href: "api/download?format=docx", kind: "docx" },
  ],
  careerStart: "2021-07",
};